### ISSUE TITLE
Add support of Solhint linter

### ISSUE THREAD

**Issue by idrabenia** [trufflesuite/truffle-compile#33]
Hi Guys,

We develop code linter that provide:
1. Strict source code validation according [Solidity Style Guide](http://solidity.readthedocs.io/en/develop/style-guide.html)
2. Security code check using [ConsenSys Guide for Smart Contracts](https://consensys.github.io/smart-contract-best-practices/recommendations/)
3. Best practices code validation

We think that it would be very helpful for community to integrate capabilities of our linter to truffle.

We may create a PR. What do you think?

Thanks!
\- Ilya

**Comment by cgewecke** [comment]
@idrabenia Hi, thanks for the suggestion. Closing this for house-keeping because I don't think this issue specifically fits in this module. How truffle integrates with external services like linters is something that under active discussion here. Will definitely reach out to you and other tools developers when we have a good sense of how to do that. 

Thanks again!
