### ISSUE TITLE
Error reporting on parsing for defined_contracts broken

### ISSUE THREAD

**Issue by maraoz** [trufflesuite/truffle-compile#6]
This doesn't work:
https://github.com/trufflesuite/truffle-compile/blob/master/profiler.js#L253-L254

If a contract has a syntax error, you don't get the file name and line number where it was found. 
Try running `truffle publish` on this project: https://github.com/OpenZeppelin/zeppelin-solidity/tree/72d31c2471f1f6eadeec63391e6f9003dddc52f4

**Comment by cgewecke** [comment]
@maraoz Thanks, this should be fixed in `4.1.5` - `defined_contracts` is no longer being run. Instead `truffle publish` expects the existing artifacts in the build folder to describe the publication set. 

Closing but please ping if you continue to see problems with `publish` / the new solution is not working adequately.
